package com.oauth.server.service;

import com.google.zxing.WriterException;
import com.oauth.server.dto.OtpSetupResponse;
import com.oauth.server.model.User;
import com.oauth.server.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.IOException;
import java.util.Base64;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

/**
 * Service for managing TOTP setup, verification, and temporary login state.
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class OtpService {

    private final TotpService totpService;
    private final UserRepository userRepository;

    /**
     * Temporary token store for OTP login flow.
     * Maps temp token -> username. Entries expire after 5 minutes.
     */
    private final ConcurrentHashMap<String, TempLoginEntry> tempLogins = new ConcurrentHashMap<>();

    /** Scheduler for cleaning up expired temp tokens. */
    private final ScheduledExecutorService cleanupScheduler =
            Executors.newSingleThreadScheduledExecutor();

    /**
     * Initialize TOTP for a user.
     * Generates a secret and returns setup information including a QR code.
     * The secret is NOT saved until the user verifies it with a code.
     *
     * @param user the user to set up TOTP for
     * @return setup response with secret, URI, and QR code
     */
    public OtpSetupResponse setupTotp(User user) throws WriterException, IOException {
        // Generate a new secret
        String secret = totpService.generateSecret();
        String otpauthUri = totpService.buildOtpauthUri(user.getUsername(), secret);
        byte[] qrCodeBytes = totpService.generateQrCode(user.getUsername(), secret);
        String qrCodeBase64 = Base64.getEncoder().encodeToString(qrCodeBytes);

        // Store the secret temporarily (not yet confirmed)
        // We store it in a pending setup cache
        pendingSetups.put(user.getUsername(), secret);

        return OtpSetupResponse.builder()
                .secret(secret)
                .otpauthUri(otpauthUri)
                .qrCodeBase64(qrCodeBase64)
                .alreadyEnabled(user.isTotpEnabled())
                .build();
    }

    /** Pending TOTP setups (username -> secret) waiting for verification. */
    private final ConcurrentHashMap<String, String> pendingSetups = new ConcurrentHashMap<>();

    /**
     * Verify and enable TOTP for a user.
     * The user provides a code generated by their authenticator app.
     * If the code is valid, TOTP is enabled for the account.
     *
     * @param user  the user enabling TOTP
     * @param code  the 6-digit code from the authenticator app
     * @return true if TOTP was successfully enabled
     */
    @Transactional
    public boolean verifyAndEnableTotp(User user, String code) {
        String secret = pendingSetups.get(user.getUsername());

        if (secret == null) {
            log.warn("No pending TOTP setup for user: {}", user.getUsername());
            return false;
        }

        // Verify the code
        if (!totpService.verifyCode(secret, code)) {
            log.warn("Invalid TOTP code during setup for user: {}", user.getUsername());
            return false;
        }

        // Enable TOTP for the user
        user.setTotpSecret(secret);
        user.setTotpEnabled(true);
        userRepository.save(user);

        // Remove from pending
        pendingSetups.remove(user.getUsername());

        log.info("TOTP enabled for user: {}", user.getUsername());
        return true;
    }

    /**
     * Disable TOTP for a user.
     *
     * @param user the user disabling TOTP
     */
    @Transactional
    public void disableTotp(User user) {
        user.setTotpSecret(null);
        user.setTotpEnabled(false);
        userRepository.save(user);
        log.info("TOTP disabled for user: {}", user.getUsername());
    }

    /**
     * Check if a user has TOTP enabled.
     */
    public boolean isTotpEnabled(User user) {
        return user.isTotpEnabled() && user.getTotpSecret() != null;
    }

    /**
     * Create a temporary login token after successful password authentication.
     * This token must be used to submit the OTP code.
     *
     * @param username the authenticated username
     * @return a temporary token valid for 5 minutes
     */
    public String createTempLogin(String username) {
        String tempToken = "tmp_" + UUID.randomUUID().toString().replace("-", "");

        tempLogins.put(tempToken, new TempLoginEntry(username, System.currentTimeMillis()));

        // Schedule cleanup after 5 minutes
        cleanupScheduler.schedule(() -> tempLogins.remove(tempToken), 5, TimeUnit.MINUTES);

        return tempToken;
    }

    /**
     * Validate a temporary login token and return the associated username.
     *
     * @param tempToken the temporary token
     * @return the username, or null if the token is invalid or expired
     */
    public String validateTempLogin(String tempToken) {
        TempLoginEntry entry = tempLogins.get(tempToken);

        if (entry == null) {
            return null;
        }

        // Check if expired (5 minutes)
        if (System.currentTimeMillis() - entry.timestamp > TimeUnit.MINUTES.toMillis(5)) {
            tempLogins.remove(tempToken);
            return null;
        }

        return entry.username;
    }

    /**
     * Remove a temporary login token (after successful OTP verification).
     */
    public void removeTempLogin(String tempToken) {
        tempLogins.remove(tempToken);
    }

    /**
     * Verify a TOTP code for a user.
     *
     * @param user the user
     * @param code the 6-digit code
     * @return true if the code is valid
     */
    public boolean verifyTotpCode(User user, String code) {
        if (!isTotpEnabled(user)) {
            return true; // TOTP not enabled, skip verification
        }
        return totpService.verifyCode(user.getTotpSecret(), code);
    }

    /**
     * Record for temporary login state.
     */
    private record TempLoginEntry(String username, long timestamp) {}
}
